name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Checks and Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Tools with mise
        uses: jdx/mise-action@v4

      - name: Run All Checks (Task)
        run: task test
